function [neighborIndex] = clusterNN(root,dataSet,testPoint)
%clusterNN 1-NN cluster search
%   clusterNN performs 1-NN search in a cluster generated by
%   hLabeledCluster for the testPoint. See nnSearchCluster for more details
%   on parameters. testPoint is a single point with dimensions 1 x D.
%   clusterNN searches the root clusters for the approximate nearest
%   neighbor, then searches the children of this root and so on and so
%   forth, i.e. it is a hierarchical cluster.
    clusterIndex=oneNN(root.cluster,testPoint);
    if(isfield(root,'child'))                                                   %root has child element, i.e. clusters
        neighborIndex=clusterNN(root.child(clusterIndex),dataSet,testPoint);
    else                                                                        %root has no subclusters, only clusters, i.e. only one level left
        neighborIndex=root.index(clusterIndex).index(oneNN(dataSet(root.index(clusterIndex).index,:),testPoint));
    end
end