function[foundLabels]=nnSearchCluster(root,trainingLabels,trainingData,testdata)
%nnSearchCluster 1-NN Cluster Search
%   nnSearchCluster searches a cluster generated by hLabeledCluster for the
%   appropriate label(s) of testdata. Input parameters are: (i) root: the root
%   of the cluster generated by the appropriate call to hLabeledCluster;
%   (ii) trainingLabels: the labels of the training set, indexed, with 
%   dimensions N x D (N: #examples, D: #dimensions of each example);
%   (iii) trainingData: the training data, indexed, with N x D dimensions;
%   and finally (iv) testdata: the collection of test points, with
%   dimension K x D. nnSearch returns indexed labels for each K in
%   testdata.
    foundLabels = zeros(size(testdata,1),1);
    if(isfield(root,'type'))
        clusterIndex=oneNNnew(root.cluster,testdata);
        foundLabels=root.labs(ceil(clusterIndex/root.perLab))';
    else
        for count=1:size(testdata,1)
                    foundLabels(count)=trainingLabels(clusterNN(root,trainingData,testdata(count,:)));
        end
    end
end